# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }
    app.zusatz_kategorie_mapper:
        class: AppBundle\Helper\ZusatzKategorieHelper
        arguments:
          doctrine: "@doctrine"
    app.cache.clear:
        class: Symfony\Bundle\FrameworkBundle\Command\CacheClearCommand
        calls:
            - [setContainer, ["@service_container"] ]
    app.cache.warmup:
            class: Symfony\Bundle\FrameworkBundle\Command\CacheWarmupCommand
            calls:
                - [setContainer, ["@service_container"] ]
